### ISSUE TITLE
Project state ?

### ISSUE THREAD

**Issue by m01001101-01010110** [bartcubbins/kernel_kanuti_mainline#2]
Hello,

Can you please tell me what is the state of this project ? Is this kernel working without issues ? Any blocking point ?
Do you know any other project for msm8939 kernel that is still being maintained/developed ?

Thank you by advance for your answers!

**Comment by bartcubbins** [comment]
There is minimal hardware support, the device can boot into the OS.
You better monitor the mainline kernel, there are guys who are still working on this device.
I don't have the strength to try to send patches to the mainline kernel, so most likely everything will remain as is.

Thanks for your interest in this!
